# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"    color: rgb(245, 245, 245);\n"
"}\n"
"\n"
"#main_frame {\n"
"    padding: 0px;\n"
"    background: rgb(35, 35, 35);\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"#product_link {\n"
"    min-height: 25px;\n"
"    \n"
"    margin-top: 5px;\n"
"    margin-bottom: 10px;\n"
"\n"
"    padding: 10px;\n"
"    background: rgb(45, 45, 45);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#product_name {\n"
"    padding: 10px;\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"}\n"
"\n"
"#product_price {\n"
"    padding: 5px;\n"
"    font: 81 16pt \"Montserrat ExtraBold\";\n"
"    background: rgb(100, 255, 100);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#product_last_price {\n"
"    padding: 5px;\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"    text-decoration: line-through;\n"
"    color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"#price_frame {\n"
"    padding: 10px;\n"
"    background: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#product_image {\n"
"    min-width: 150px;\n"
"    min-height: 150px;\n"
"\n"
"    max-width: 150px;\n"
"    max-height: 150px;\n"
"\n"
"    margin-right: 15px;\n"
"\n"
"    padding: 10px;\n"
"    background: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#prices_frame {\n"
"    margin-top: 10px;\n"
"\n"
"    padding: 10px;\n"
"    padding-top: 0px;\n"
"    background: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#product_prices {\n"
"    padding: 10px;\n"
"    background: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#prices_label {\n"
"    padding: 10px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    width: 10px;\n"
"     background: rgba(0, 0, 0, 0);\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"    background: rgb(100, 255, 100);\n"
"    border-radius: 5px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     height: 0px;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     width: 0px;\n"
"     height: 0px;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: rgba(0, 0, 0, 0.1);\n"
"    border-radius: 5px;\n"
" }\n"
"\n"
"#close_frame {\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"#close_button {\n"
"    background: rgb(255, 100, 100);\n"
"    border-radius: 6px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.close_frame = QtWidgets.QFrame(self.main_frame)
        self.close_frame.setMinimumSize(QtCore.QSize(0, 20))
        self.close_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame.setLineWidth(0)
        self.close_frame.setObjectName("close_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.close_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(self.close_frame)
        self.close_button.setMinimumSize(QtCore.QSize(12, 12))
        self.close_button.setMaximumSize(QtCore.QSize(12, 12))
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_4.addWidget(self.close_button)
        self.verticalLayout.addWidget(self.close_frame)
        self.product_link = QtWidgets.QLineEdit(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_link.sizePolicy().hasHeightForWidth())
        self.product_link.setSizePolicy(sizePolicy)
        self.product_link.setMinimumSize(QtCore.QSize(0, 60))
        self.product_link.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.product_link.setStyleSheet("")
        self.product_link.setText("")
        self.product_link.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.product_link.setAlignment(QtCore.Qt.AlignCenter)
        self.product_link.setDragEnabled(True)
        self.product_link.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.product_link.setClearButtonEnabled(False)
        self.product_link.setObjectName("product_link")
        self.verticalLayout.addWidget(self.product_link)
        self.frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.product_image_frame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_image_frame.sizePolicy().hasHeightForWidth())
        self.product_image_frame.setSizePolicy(sizePolicy)
        self.product_image_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.product_image_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.product_image_frame.setObjectName("product_image_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.product_image_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.product_image = QtWidgets.QLabel(self.product_image_frame)
        self.product_image.setLineWidth(0)
        self.product_image.setText("")
        self.product_image.setObjectName("product_image")
        self.verticalLayout_3.addWidget(self.product_image)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.product_image_frame)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.product_name = QtWidgets.QLabel(self.frame_2)
        self.product_name.setMinimumSize(QtCore.QSize(250, 0))
        self.product_name.setMaximumSize(QtCore.QSize(500, 16777215))
        self.product_name.setWordWrap(True)
        self.product_name.setObjectName("product_name")
        self.verticalLayout_2.addWidget(self.product_name)
        self.price_frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_frame.sizePolicy().hasHeightForWidth())
        self.price_frame.setSizePolicy(sizePolicy)
        self.price_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_frame.setObjectName("price_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.price_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.product_price = QtWidgets.QLabel(self.price_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_price.sizePolicy().hasHeightForWidth())
        self.product_price.setSizePolicy(sizePolicy)
        self.product_price.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.product_price.setFont(font)
        self.product_price.setObjectName("product_price")
        self.horizontalLayout_2.addWidget(self.product_price)
        self.product_last_price = QtWidgets.QLabel(self.price_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_last_price.sizePolicy().hasHeightForWidth())
        self.product_last_price.setSizePolicy(sizePolicy)
        self.product_last_price.setObjectName("product_last_price")
        self.horizontalLayout_2.addWidget(self.product_last_price)
        self.verticalLayout_2.addWidget(self.price_frame)
        self.prices_frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prices_frame.sizePolicy().hasHeightForWidth())
        self.prices_frame.setSizePolicy(sizePolicy)
        self.prices_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.prices_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prices_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prices_frame.setObjectName("prices_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.prices_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.prices_label = QtWidgets.QLabel(self.prices_frame)
        self.prices_label.setMinimumSize(QtCore.QSize(250, 0))
        self.prices_label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.prices_label.setWordWrap(True)
        self.prices_label.setObjectName("prices_label")
        self.verticalLayout_4.addWidget(self.prices_label)
        self.product_prices = QtWidgets.QListWidget(self.prices_frame)
        self.product_prices.setStyleSheet("")
        self.product_prices.setObjectName("product_prices")
        self.verticalLayout_4.addWidget(self.product_prices)
        self.verticalLayout_2.addWidget(self.prices_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.product_name.setText(_translate("MainWindow", "-"))
        self.product_price.setText(_translate("MainWindow", "0 ₽"))
        self.product_last_price.setText(_translate("MainWindow", "0 ₽"))
        self.prices_label.setText(_translate("MainWindow", "Динамика цен"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
